# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "uas" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/nixos-enc";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."nixos-enc".device = "/dev/disk/by-uuid/5290c5e3-703d-4ac9-b54c-82e74d5fca35";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/171D-19FB";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [
    {
      device = "/dev/disk/by-partuuid/f56da4bf-3e68-4c8f-babd-dc32e794a7ca";
      randomEncryption.enable = true;
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
