{ ... }: {
  # Forgejo (self-hosted git forge) — used on evo as a safe mirror + review buffer
  # between the Hermes agent and GitHub.
  #
  #   GitHub (public) --pull-mirror--> simon/nixos-config   (read-only, auto-synced main)
  #                                         ^ fork
  #                                    hermes/nixos-config   (Hermes pushes branches, opens PRs)
  #
  # Hermes reaches Forgejo over the host network on 127.0.0.1 with a scoped token; it holds
  # no GitHub credentials and cannot push to the mirror. You review PRs in the UI, download the
  # patch, and forward it to GitHub from your own workstation. See ../../machines/evo/hermes.nix.
  #
  # Internal secrets (SECRET_KEY / INTERNAL_TOKEN / JWT secrets) are generated by the NixOS
  # module on first start and kept in the state dir — no sops entry needed for those.
  # The admin password IS provisioned from sops (forgejo-admin-password) via the bootstrap
  # oneshot below.
  #
  # Required sops secrets (add with `sops secrets/secrets.yaml`):
  #   forgejo-admin-password : password for the bootstrapped admin user (this module).
  #   forgejo-hermes-token   : Forgejo access token for the `hermes` account (hermes.nix).
  # Add both BEFORE the first deploy or activation fails. `forgejo-hermes-token` can start as any
  # placeholder — the real token doesn't exist until step 2 below; swap it in and redeploy.
  #
  # One-time setup after the first `deploy .#evo` (Forgejo repos/accounts are runtime state):
  #   1. Log into the UI (http://192.168.1.105:3000 or https://git.simon-wick.ch) as the admin.
  #   2. Create the `hermes` user; make an access token for it -> put in sops as
  #      forgejo-hermes-token; redeploy so the container picks it up.
  #   3. New Migration -> https://github.com/Ilosariph/nixos-config.git, owner=simon,
  #      name=nixos-config, tick "This repository will be a mirror".
  #   4. As hermes, fork simon/nixos-config -> hermes/nixos-config.
  #   5. (optional, instant sync) Expose git.simon-wick.ch -> evo:httpPort on the Pangolin
  #      server, then add a GitHub push webhook -> /api/v1/repos/simon/nixos-config/mirror-sync.
  flake.nixosModules.forgejo = { config, lib, ... }:
    let
      cfg = config.dotfiles.services.forgejo;
      forgejo = "${config.services.forgejo.package}/bin/forgejo";
      admin = config.dotfiles.user.name;
      adminEmail = "simonwickch@gmail.com";
      pwFile = config.sops.secrets."forgejo-admin-password".path;
    in
    lib.mkIf cfg.enable {
      services.forgejo = {
        enable = true;
        database.type = "sqlite3";
        settings = {
          server = {
            DOMAIN = cfg.domain;
            ROOT_URL = "https://${cfg.domain}/";
            HTTP_ADDR = "0.0.0.0";
            HTTP_PORT = cfg.httpPort;
          };
          # Admin-only account creation; Hermes + you are created by hand / API.
          service.DISABLE_REGISTRATION = true;
          # Pull-mirrors poll on this interval (10m is the built-in minimum). Combine with a
          # GitHub push webhook -> /api/v1/repos/<owner>/<repo>/mirror-sync for near-instant sync.
          mirror = {
            ENABLED = true;
            DEFAULT_INTERVAL = "10m";
          };
        };
      };

      # Admin password comes from sops; readable by the forgejo service user (which the
      # bootstrap oneshot runs as).
      sops.secrets."forgejo-admin-password" = {
        owner = config.services.forgejo.user;
        group = config.services.forgejo.group;
        mode = "0400";
      };

      # Idempotently create the initial admin user after Forgejo is up. Skips if it already
      # exists, so it is safe to run on every activation.
      systemd.services.forgejo-admin-bootstrap = {
        description = "Create the initial Forgejo admin user";
        after = [ "forgejo.service" ];
        requires = [ "forgejo.service" ];
        wantedBy = [ "multi-user.target" ];
        environment = {
          GITEA_WORK_DIR = config.services.forgejo.stateDir;
          GITEA_CUSTOM = config.services.forgejo.customDir;
        };
        serviceConfig = {
          Type = "oneshot";
          User = config.services.forgejo.user;
          Group = config.services.forgejo.group;
        };
        script = ''
          set -eu
          if ${forgejo} admin user list --admin | awk '{print $2}' | grep -qx ${admin}; then
            echo "admin user ${admin} already exists, skipping"
          else
            ${forgejo} admin user create \
              --admin \
              --username ${admin} \
              --email ${adminEmail} \
              --password "$(cat ${pwFile})" \
              --must-change-password=false
          fi
        '';
      };

      networking.firewall.allowedTCPPorts = [ cfg.httpPort ];
    };
}
