# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."bazarr" = {
    image = "ghcr.io/hotio/bazarr:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "Europe/Zurich";
    };
    volumes = [
      "/etc/localtime:/etc/localtime:ro"
      "/home/simon/docker/arr/bazarr:/config:rw"
      "/mnt/arr/media:/data/media:rw"
    ];
    ports = [
      "6767:6767/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--hostname=bazarr.internal"
      "--network-alias=bazarr"
      "--network=arr_arr-internal"
    ];
  };
  systemd.services."docker-bazarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-arr_arr-internal.service"
    ];
    requires = [
      "docker-network-arr_arr-internal.service"
    ];
    partOf = [
      "docker-compose-arr-root.target"
    ];
    upheldBy = [
      "docker-network-arr_arr-internal.service"
    ];
    wantedBy = [
      "docker-compose-arr-root.target"
    ];
  };
  virtualisation.oci-containers.containers."lidarr" = {
    image = "ghcr.io/hotio/lidarr";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "Etc/UTC";
      "UMASK" = "002";
    };
    volumes = [
      "/home/simon/docker/arr/lidarr:/config:rw"
      "/mnt/arr:/data:rw"
    ];
    ports = [
      "8686:8686/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--hostname=lidarr.internal"
      "--network-alias=lidarr"
      "--network=arr_arr-internal"
    ];
  };
  systemd.services."docker-lidarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-arr_arr-internal.service"
    ];
    requires = [
      "docker-network-arr_arr-internal.service"
    ];
    partOf = [
      "docker-compose-arr-root.target"
    ];
    upheldBy = [
      "docker-network-arr_arr-internal.service"
    ];
    wantedBy = [
      "docker-compose-arr-root.target"
    ];
  };
  virtualisation.oci-containers.containers."prowlarr" = {
    image = "lscr.io/linuxserver/prowlarr:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "Europe/Zurich";
    };
    volumes = [
      "/etc/localtime:/etc/localtime:ro"
      "/home/simon/docker/arr/prowlarr:/config:rw"
    ];
    ports = [
      "9696:9696/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--hostname=prowlarr.internal"
      "--network-alias=prowlarr"
      "--network=arr_arr-internal"
      "--network=mediathekarr"
    ];
  };
  systemd.services."docker-prowlarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-arr_arr-internal.service"
    ];
    requires = [
      "docker-network-arr_arr-internal.service"
    ];
    partOf = [
      "docker-compose-arr-root.target"
    ];
    upheldBy = [
      "docker-network-arr_arr-internal.service"
    ];
    wantedBy = [
      "docker-compose-arr-root.target"
    ];
  };
  virtualisation.oci-containers.containers."radarr" = {
    image = "ghcr.io/hotio/radarr:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "Europe/Zurich";
    };
    volumes = [
      "/etc/localtime:/etc/localtime:ro"
      "/home/simon/docker/arr/radarr:/config:rw"
      "/mnt/arr:/data:rw"
    ];
    ports = [
      "7878:7878/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--hostname=radarr.internal"
      "--network-alias=radarr"
      "--network=arr_arr-internal"
      "--network=jellyseerr"
      "--network=mediathekarr"
      "--network=recommendarr"
      "--network=recyclarr"
    ];
  };
  systemd.services."docker-radarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-arr_arr-internal.service"
    ];
    requires = [
      "docker-network-arr_arr-internal.service"
    ];
    partOf = [
      "docker-compose-arr-root.target"
    ];
    upheldBy = [
      "docker-network-arr_arr-internal.service"
    ];
    wantedBy = [
      "docker-compose-arr-root.target"
    ];
  };
  virtualisation.oci-containers.containers."sabnzbd" = {
    image = "ghcr.io/hotio/sabnzbd:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "Europe/Zurich";
    };
    volumes = [
      "/etc/localtime:/etc/localtime:ro"
      "/home/simon/docker/arr/sabnzbd:/config:rw"
      "/mnt/arr/usenet:/data/usenet:rw"
    ];
    ports = [
      "8080:8080/tcp"
      "9090:9090/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--hostname=sabnzbd.internal"
      "--network-alias=sabnzbd"
      "--network=arr_arr-internal"
    ];
  };
  systemd.services."docker-sabnzbd" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-arr_arr-internal.service"
    ];
    requires = [
      "docker-network-arr_arr-internal.service"
    ];
    partOf = [
      "docker-compose-arr-root.target"
    ];
    upheldBy = [
      "docker-network-arr_arr-internal.service"
    ];
    wantedBy = [
      "docker-compose-arr-root.target"
    ];
  };
  virtualisation.oci-containers.containers."sonarr" = {
    image = "ghcr.io/hotio/sonarr:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "Europe/Zurich";
    };
    volumes = [
      "/etc/localtime:/etc/localtime:ro"
      "/home/simon/docker/arr/sonarr:/config:rw"
      "/mnt/arr:/data:rw"
    ];
    ports = [
      "8989:8989/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--hostname=sonarr.internal"
      "--network-alias=sonarr"
      "--network=arr_arr-internal"
      "--network=jellyseerr"
      "--network=mediathekarr"
      "--network=recommendarr"
      "--network=recyclarr"
    ];
  };
  systemd.services."docker-sonarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-arr_arr-internal.service"
    ];
    requires = [
      "docker-network-arr_arr-internal.service"
    ];
    partOf = [
      "docker-compose-arr-root.target"
    ];
    upheldBy = [
      "docker-network-arr_arr-internal.service"
    ];
    wantedBy = [
      "docker-compose-arr-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-arr_arr-internal" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f arr_arr-internal";
    };
    script = ''
      docker network inspect arr_arr-internal || docker network create arr_arr-internal
    '';
    partOf = [ "docker-compose-arr-root.target" ];
    wantedBy = [ "docker-compose-arr-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-arr-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
